echo off
echo Starting now... $(stamp)
echo Generating new spreadsheet...
node criar_planilha.js
echo Generating week_day...
node gerar_week_day.js
echo Generating month...
node gerar_month.js
echo Generating shift...
node filtrar_shift.js
echo Filtering type...
node filtrar_type.js
echo Filtering client...
node filtrar_clientes.js
echo Filtering severities...
node filtrar_severidades.js
echo Filtering labels...
node filtrar_labels.js
pause